jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        WordRot\PlayBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        wordnik_users:
            entity: { class: WordRotPlayBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        wordnik_secured:
            pattern:   ^/play
            anonymous: true
            wordnik:   true
            wordnik:
                provider:  wordnik_users
                default_target_path: play
                check_path: login_check
            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/play, roles: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }