jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        wordnik_users:
            entity: { class: WordRotPlayBundle:User, property: username }

    firewalls:
        wordnik_secured:
            pattern: ^/play
            logout: ~
            anonymous: ~
            wordnik: true
            form_login:
                provider: wordnik_users
                login_path:  /login
                check_path:  /login_check

    access_control:
        - { path: ^/play, roles: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }