homepage:
    pattern:  /
    defaults: { _controller: WordRotPlayBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: WordRotPlayBundle:Default:login }

login_check:
    pattern:   /play/check

logout:
    pattern:   /play/logout

play:
    pattern: /play
    defaults: { _controller: WordRotPlayBundle:Play:index }

# # # # # # # #
# REST Routes #
# # # # # # # #

users_get:
    pattern: /play/users/{id}
    defaults:
        _controller: WordRotPlayBundle:Users:get
        _format: json
    requirements:
        _method: GET
        id: "\d+"

lists_get:
    pattern: /play/lists
    defaults:
        _controller: WordRotPlayBundle:Lists:all
        _format: json
    requirements: { _method: GET }