homepage:
    pattern:  /
    defaults: { _controller: WordRotPlayBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: WordRotPlayBundle:Default:login }

login_check:
    pattern:   /play/check

logout:
    pattern:   /play/logout

play:
    pattern: /play
    defaults: { _controller: WordRotPlayBundle:Play:index }