parameters:
#    word_rot_play.example.class: WordRot\PlayBundle\Example

services:
#    word_rot_play.example:
#        class: %word_rot_play.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
