parameters:
   word_rot_play.wordnik.class: WordRot\PlayBundle\Service\Wordnik
   word_rot_play.wordnik.api_url: 'http://api.wordnik.com/v4'

services:
    word_rot_play.wordnik:
        # NOTE: Must define `wordnik_api_key` in parameters.yml
        class: %word_rot_play.wordnik.class%
        arguments: [@service_container, %wordnik_api_key%, %word_rot_play.wordnik.api_url%]

    wordnik.security.authentication.provider:
        class:  WordRot\PlayBundle\Security\Authentication\Provider\WordnikProvider
        arguments: ['', @word_rot_play.wordnik]

    wordnik.security.authentication.listener:
        class:  WordRot\PlayBundle\Security\Firewall\WordnikListener
        arguments: [@security.context, @security.authentication.manager]