parameters:
   word_rot_play.wordnik.class: WordRot\PlayBundle\Service\Wordnik
   word_rot_play.wordnik.api_url: 'http://api.wordnik.com/v4'

services:
   # NOTE: Must define `wordnik_api_key` in parameters.yml
   word_rot_play.wordnik:
       class: %word_rot_play.wordnik.class%
       arguments: [@service_container, %wordnik_api_key%, %word_rot_play.wordnik.api_url%]
